- name: Play Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "{{ URL }}"
# In ansible we access variable with {{ }}
# Also, if the value is variable or starts with variable then we need to quote it ( Double quotes preferred)
# key: "{{ val }}"
# key: "{{ val }} some-other string"
# key: some - {{ val }}      # this does not require quotes.

- name: Task Variables
  hosts: localhost
  connection: local
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
         URL: task.google.com

- name: Role Variables
  hosts: localhost
  connection: local
  roles:
    - demo

# We can also give variables from command line interface using -e option [ Extra variable]
# $ansible-playbook 03-vars.yml -e URL=cli.google.com
#In this case the values of URL is replaced with cli variable i.e cli.google.com at all levels [ Play,Tast and Role]
# If the same variable name comes in different locations then precedence will come.
# 1. CLI variable
# 2. Task variable
# 3. Role variable
# 4. Play variable

#If there is no value for a variable then defaults comes into picture
  #defaults/         #
  #main.yml      #  <-- default lower priority variables for this role

# Variables are now three types

# 1. Normal
# vars:
#   URL: example.com

# 2. List
# vars:
#   URLS:
#     - app1.example.com
#     - app2.example.com
# {{ URLS[0] }}

# 3. Map
# vars
#   URLS:
#     app1: app1.example.com
#     app2: app2.example.com
#{{ URLS.app1 }}

# Variable also have data types
# 1. String
# 2. Number
# 3. Boolean ( True/False , Yes/No, )