- name: Templates
  hosts: localhost
  connection: local
  tasks:
    - name: File copy
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt

#git pull; ansible-playbook 07-templates.yml -e name=Sai