- name: Ansible Vault
  hosts: localhost
  connection: local
  vars:
    password: Saiteja@321
    tasks:
      - name: Print Password
        ansible.builtin.debug:
          msg: Password - {{ password }}